In [1]:
%matplotlib inline
import torch, torchvision
from torch.autograd import Variable

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [4]:
print(x)
print(y)
print(type(y))
print(w)
print(type(w))
print(b)
print(type(b))
print(z)
print(type(z))
print(loss)
print(type(loss))

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])
<class 'torch.Tensor'>
tensor([[ 0.7763, -1.3243,  0.1120],
        [-0.5512,  0.1474,  0.8871],
        [-1.6610, -0.6395,  0.6719],
        [-0.8930, -0.8959, -0.7859],
        [-2.0869, -0.5260,  0.6045]], requires_grad=True)
<class 'torch.Tensor'>
tensor([-0.5457, -0.1320,  0.6375], requires_grad=True)
<class 'torch.Tensor'>
tensor([-4.9615, -3.3705,  2.1271], grad_fn=<AddBackward0>)
<class 'torch.Tensor'>
tensor(0.7602, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
<class 'torch.Tensor'>


In [5]:
print(loss.grad_fn)

In [7]:
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)
print(type(x))

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
<class 'torch.Tensor'>


In [8]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [9]:
print(y.grad_fn)

In [10]:
z = y * y * 3
out = z.mean()

print(z)
print("---"*5)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
---------------
tensor(27., grad_fn=<MeanBackward0>)


In [11]:
print(y.grad_fn)

In [12]:
out.backward()

In [13]:
print(x.grad) # out을 통해서 구하는 것
# out = 1/4 * 3(xi + 2)^2

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [37]:
x = torch.randn(3)
print(x)
x = Variable(x, requires_grad = True)
print(x)

y = x * 2
print(y.data.norm()) # 제곱들 합의 루트, 즉 
while y.data.norm() < 1000:
    y = y * 2
    print(y)
print(y)

tensor([-0.5351,  1.2386,  0.2366])
tensor([-0.5351,  1.2386,  0.2366], requires_grad=True)
tensor(2.7396)
tensor([-2.1406,  4.9542,  0.9464], grad_fn=<MulBackward0>)
tensor([-4.2812,  9.9084,  1.8927], grad_fn=<MulBackward0>)
tensor([-8.5623, 19.8168,  3.7854], grad_fn=<MulBackward0>)
tensor([-17.1246,  39.6337,   7.5709], grad_fn=<MulBackward0>)
tensor([-34.2492,  79.2673,  15.1417], grad_fn=<MulBackward0>)
tensor([-68.4984, 158.5347,  30.2834], grad_fn=<MulBackward0>)
tensor([-136.9968,  317.0693,   60.5669], grad_fn=<MulBackward0>)
tensor([-273.9936,  634.1386,  121.1337], grad_fn=<MulBackward0>)
tensor([-547.9872, 1268.2772,  242.2674], grad_fn=<MulBackward0>)
tensor([-547.9872, 1268.2772,  242.2674], grad_fn=<MulBackward0>)


In [39]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [19]:
y

tensor([ -906.3586, -1432.2189,    73.1209], grad_fn=<MulBackward0>)